/* ============================================================
   PROJECT DATA
   Every entry below is a real client / employer engagement.
   Edit this file to add, remove, or update project write-ups —
   the page renders itself from this array, nothing else to touch.
   ============================================================ */

const PROJECTS = [
  {
    id: "instarag",
    name: "InstaRAG",
    kicker: "Self-Service Agentic RAG Platform",
    org: "Freelance - Client Engagement",
    categories: ["genai", "agentic"],
    tags: ["LangGraph", "RAG", "LangSmith", "Langfuse", "MCP", "Guardrails"],
    video: "assets/media/instarag.mp4",
    poster: "assets/media/instarag-poster.jpg",
    hook: "Turned a weeks-long, engineer-gated demo pipeline into a self-service chatbot builder for sales.",
    stats: [
      { value: "95%", label: "Less demo-build effort" },
      { value: "99%", label: "Citation-grounded answers" },
      { value: "40%+", label: "Uplift in sales figures" },
    ],
    challenge: [
      "Every customer demo needed engineering time to crawl sites, ingest documents, wire up retrieval, and build a bespoke chatbot — stretching delivery from days to weeks.",
      "Each prospect needed an isolated knowledge base with zero data leakage between workspaces, plus secure sharing and lifecycle management.",
      "Generic LLM answers were often inaccurate or unsupported — unacceptable in front of a customer.",
      "Prompt failures, retrieval quality, and tool execution were near-impossible to debug without end-to-end tracing and evaluation.",
    ],
    solution: [
      "Designed an end-to-end self-service Agentic RAG platform so sales teams can spin up chatbot demos with no engineering support.",
      "Built isolated per-tenant workspaces with automated website crawling, PDF ingestion, semantic chunking, metadata enrichment, and per-tenant vector indexing.",
      "Built a LangGraph multi-agent orchestration layer combining retrieval, web search, and MCP tools with guardrails to produce citation-backed answers grounded in the customer's own data.",
      "Wired in LangSmith and Langfuse for prompt evaluation, trace analysis, retrieval debugging, and ongoing optimisation.",
    ],
  },
  {
    id: "adcities",
    name: "Adcities",
    kicker: "AI-Powered Out-of-Home (OOH) Measurement & Analytics Platform",
    org: "Global Nodes — Client Engagement",
    categories: ["data", "agentic", "geospatial"],
    tags: ["Apache Sedona", "Databricks", "Medallion Lakehouse", "LangGraph", "PySpark"],
    video: "assets/media/adcities.mp4",
    poster: "assets/media/adcities-poster.jpg",
    hook: "Owned the vision, architecture, and delivery of a three-phase platform measuring and explaining out-of-home ad performance across 130M+ daily records.",
    stats: [
      { value: "130M+", label: "Records processed daily" },
      { value: "99%", label: "Pipeline uptime" },
      { value: "70%+", label: "Better attribution accuracy" },
    ],
    phases: [
      {
        title: "Phase 1 — OOH Measurement Platform",
        challenge: "OOH has no deterministic user interactions like digital ads, static industry KPIs assumed equal visibility for every passerby, and mobility, traffic, weather, and asset data lived in separate systems — while 130M+ GPS and mobility records needed geospatial mapping to advertising assets every day.",
        solution: "Architected an enterprise-scale Medallion lakehouse for ingestion, validation, and lineage; built Apache Sedona geospatial attribution pipelines; re-engineered core OOH KPIs into multi-factor Realistic Affinity Models; automated KPI generation, attribution, and reporting.",
      },
      {
        title: "Phase 2 — Agentic Campaign Intelligence",
        challenge: "Traditional BI could flag a KPI change but not explain it — analysts spent hours manually correlating performance against weather, events, traffic, and holidays scattered across systems.",
        solution: "Built an agentic orchestration framework that autonomously investigates campaign performance against public events, news, government advisories, traffic, and historical trends, then produces citation-backed explanations in natural language instead of static dashboards.",
      },
      {
        title: "Phase 3 — Context-Aware Media Recommendation Engine",
        challenge: "The platform measured campaigns after the fact but gave no guidance beforehand — media selection relied on planner intuition rather than a decision-intelligence system.",
        solution: "Designed a decision-intelligence engine combining historical performance with real-time mobility, event, traffic, demographic, and POI-affinity signals, ranked through a multi-factor scoring engine that returns explainable recommendations with confidence scores.",
      },
    ],
    challenge: [
      "OOH lacks deterministic user interactions, making impressions, reach, frequency, and effectiveness hard to measure accurately.",
      "Traditional KPIs assumed equal visibility for every passerby, ignoring viewing angle, dwell time, traffic flow, weather, and asset characteristics.",
      "130M+ GPS and mobility records needed to be mapped to millions of advertising assets and POIs every day.",
      "Mobility, traffic, weather, demographic, asset, and campaign data were fragmented across systems.",
    ],
    solution: [
      "Architected an enterprise-scale lakehouse on Medallion architecture for reliable ingestion, validation, lineage, and analytics.",
      "Built high-performance geospatial attribution pipelines with Apache Sedona to map mobility signals to advertising assets.",
      "Re-engineered core OOH KPIs into Realistic Affinity Models combining multiple contextual factors.",
      "Layered an agentic explanation flow and a context-aware recommendation engine on top of the same warehouse (see phases above).",
    ],
  },
  {
    id: "postop-genai",
    name: "Post-Operative Care Companion",
    kicker: "Enhancing Post-operative Communication & Care with Generative AI",
    org: "Global Nodes — Client Engagement",
    categories: ["genai", "healthcare"],
    tags: ["Instruction-Tuned LLM", "Conversational AI", "Connected Hardware"],
    hook: "An instruction-tuned conversational AI to keep patients and providers connected after surgery, backed by connected monitoring hardware.",
    stats: [
      { value: "45%", label: "Target lift in comms accuracy" },
      { value: "60%", label: "Target lift in engagement" },
      { value: "30%", label: "Target cut in monitoring errors" },
    ],
    challenge: [
      "Continuous, personalised communication between patients and providers is critical after surgery, but traditional channels rarely give timely, tailored updates.",
      "The shift toward outpatient surgery left a care vacuum, with limited workforce and infrastructure to monitor recovering patients in real time.",
    ],
    solution: [
      "Instruction-tuned a large language model for healthcare-specific communication.",
      "Built a generative AI conversational system aimed at lifting patient engagement.",
      "Integrated and calibrated custom monitoring hardware to report patient readings directly into the loop, reducing manual monitoring errors.",
    ],
  },
  {
    id: "isense-partfailure",
    name: "I-Sense",
    kicker: "AI-Driven Smart Monitoring for Automotive Part-Failure Analysis",
    org: "Unthinkable Solutions — Client: Maruti Suzuki (CMMI Level 5)",
    categories: ["cv", "manufacturing"],
    tags: ["DeiT", "UNet", "Segmentation", "Materials Classification"],
    video: "assets/media/autotech.mp4",
    poster: "assets/media/autotech-poster.jpg",
    hook: "Replaced a manual, expert-only microscope review with a two-stage vision pipeline that reads fracture type and crack direction automatically.",
    stats: [
      { value: "60 hr → 2 min", label: "Per report cycle" },
      { value: "95%", label: "Prediction accuracy" },
    ],
    challenge: [
      "Analysing fracture type and crack/force propagation in motor parts was meticulous, slow, and dependent entirely on expert judgement.",
      "The existing process couldn't flex to handle ad-hoc or emergency assessments.",
    ],
    solution: [
      "Ran data collection and manual labelling with Maruti's material experts, experimenting across 309 models spanning 27 plastic and rubber grades at magnifications from 10X to 200X.",
      "Selected two production models per category: a DeiT-based classifier for damage type (brittle vs. ductile) and a UNet segmenter for crack-propagation direction.",
      "Built a full platform for user interaction and automated PDF report generation for manual sign-off.",
      "This is the same engagement as the resume's 'Part Failure Microscopic Image Analytics' project — a DeiT material classifier routes each image to a material-specific UNet segmenter, which isolates fracture regions and traces the fracture path with directional arrows, hitting 90%+ accuracy and saving ~60 hours per report cycle.",
    ],
  },
  {
    id: "maruti-airbag",
    name: "Airbag Deployment Analysis",
    kicker: "AI-Powered Airbag Deployment Analysis Platform",
    org: "Unthinkable Solutions — Client: Maruti Suzuki",
    categories: ["cv", "manufacturing"],
    tags: ["UNet", "SAM", "SageMaker Ground Truth", "5000 FPS Video"],
    video: "assets/media/airbag-front.mp4",
    poster: "assets/media/airbag-front-poster.jpg",
    hook: "Automated frame-level detection of tear-through, shoulder-reach, and full deployment across synchronised 5,000fps crash-test cameras.",
    stats: [
      { value: "35 hr → 40 s", label: "Per report cycle" },
      { value: "99%", label: "Prediction accuracy" },
    ],
    challenge: [
      "Validating airbag deployment meant engineers manually reviewing ultra-high-speed (5,000 FPS) crash videos to spot critical events — slow, subjective, and hard to scale.",
      "Pinpointing tear initiation, shoulder-point reach, and full deployment across synchronised front- and side-view cameras took heavy expert involvement.",
      "Variation in camera angle, airbag shape, deployment speed, and video quality hurt consistency and repeatability.",
    ],
    solution: [
      "Designed and shipped an end-to-end computer vision platform to automatically flag critical deployment events from synchronised high-speed footage.",
      "Built a 36K+ frame annotated dataset on Amazon SageMaker Ground Truth, and trained UNet and SAM segmentation models for multi-view airbag detection.",
      "Built an automated inference pipeline for frame extraction, segmentation, boundary tracking, and event detection.",
      "Delivered a production-ready solution — post-processing, backend APIs, frontend app, automated reporting, and deployment docs.",
    ],
  },
  {
    id: "retail-anomaly",
    name: "Order Anomaly Guard",
    kicker: "Multi-Tenant Anomaly Detection for a Retail Platform",
    org: "Unthinkable Solutions — Client Engagement",
    categories: ["data", "retail"],
    poster: "assets/media/order-anomaly-airflow.png",
    tags: ["H2O.ai", "MLflow", "Multi-Tenant ML", "Data Drift"],
    hook: "A false-positive-aware anomaly detector protecting order integrity for a multi-tenant retail platform with wildly different baselines per client.",
    stats: [
      { value: "92%", label: "Anomaly-detection accuracy" },
      { value: "10,000", label: "Orders/day across clients" },
    ],
    challenge: [
      "Anomalies — unusual product combinations, bad data, unusually large or small orders — risked operational and financial damage across many tenants with very different order patterns, seasonality, and baselines.",
      "Deploying, monitoring, and tracking a multi-tenant ML architecture at scale, per client company, was a significant engineering challenge on its own.",
    ],
    solution: [
      "Built an H2O-based anomaly detection model with MLflow experiment tracking, tuned so false-positive control mattered as much as recall.",
      "Designed a scalable multi-tenant architecture to deploy, monitor, and track the model per client company.",
      "Delivered real-time monitoring plus data-drift and data-quality reports so performance stayed honest as upstream data shifted.",
    ],
  },
  {
    id: "radiology-chestxray",
    name: "Radiology Imaging — Phase 1",
    kicker: "Chest X-Ray: Normal vs. Abnormal Classification",
    org: "Unthinkable Solutions — Healthcare Client Engagement",
    categories: ["cv", "healthcare"],
    poster: "assets/media/radiology-phase1-chestxray.png",
    tags: ["Multi-Stage Classification", "Data Augmentation"],
    hook: "First stage of a radiology imaging framework — screening chest X-rays, then telling bacterial pneumonia apart from viral.",
    stats: [
      { value: "95%+", label: "Normal vs. pneumonia accuracy" },
      { value: "92%+", label: "Bacterial vs. viral accuracy" },
      { value: "80%", label: "Less manual screening effort" },
    ],
    challenge: [
      "Labelled medical imaging datasets were limited and highly variable in quality.",
      "Distinguishing normal from pneumonia cases — and then bacterial from viral pneumonia — added a second layer of difficulty.",
      "Contrast, noise, and resolution differences across imaging conditions hurt model performance.",
    ],
    solution: [
      "Built a radiology classification framework on chest X-ray datasets with augmentation accelerators for dataset diversity and robustness.",
      "Developed a two-stage pipeline: Stage 1 flags normal vs. abnormal, Stage 2 splits pneumonia into bacterial vs. viral.",
      "Created reusable pipelines for dataset structuring, preprocessing, and training so later phases could reuse the same scaffolding.",
    ],
  },
  {
    id: "radiology-fracture",
    name: "Radiology Imaging — Phase 2",
    kicker: "Bone Fracture Detection Across X-Ray & MRI",
    org: "Unthinkable Solutions — Healthcare Client Engagement",
    poster: "assets/media/radiology-phase2-fracture.png",
    categories: ["cv", "healthcare"],
    tags: ["Object Detection", "Multi-Modal Imaging"],
    hook: "Multi-modal fracture localisation to help radiologists catch subtle breaks faster.",
    stats: [
      { value: "97%", label: "Fracture-detection accuracy" },
      { value: "70%", label: "Faster report generation" },
      { value: "65%", label: "Better workflow efficiency" },
    ],
    challenge: [
      "Subtle or complex fractures carry a high risk of misdiagnosis, and manual X-ray/MRI interpretation is slow and expertise-dependent.",
      "Variability across imaging modalities (X-ray, CT, MRI) made model generalisation harder.",
    ],
    solution: [
      "Built an AI fracture-detection system spanning X-ray, CT, and MRI data with object detection and localisation models.",
      "Integrated radiology frameworks and preprocessing pipelines for consistent input handling across modalities.",
      "Designed for real-time inference and clinical workflow integration, surfacing fracture regions to assist — not replace — radiologists.",
    ],
  },
  {
    id: "radiology-reliability",
    name: "Radiology Imaging — Phase 3",
    kicker: "Production-Grade Radiology AI Reliability",
    org: "Unthinkable Solutions — Healthcare Client Engagement",
    poster: "assets/media/radiology-phase3-views.png",
    categories: ["cv", "healthcare"],
    tags: ["EfficientNet", "ConvNeXt", "DeiT", "DICOM Pipelines"],
    hook: "Closed the gap between a model that works in a notebook and one that survives production — benchmarked, augmented, and standardised for clinical reliability.",
    stats: [],
    challenge: [
      "Medical imaging models often fail in production: poor generalisation on real-world data, small imbalanced datasets, unstable predictions across image variations (LAT vs. PA, gender, resolution), no standardised pipeline for reproducibility, and a high risk of false negatives.",
    ],
    solution: [
      "Built robust DICOM → filtered → standardised data pipelines and a 3× dataset-expansion augmentation strategy for low-data scenarios.",
      "Benchmarked EfficientNet, ConvNeXt, and DeiT architectures, added a hyperparameter and resolution-scaling optimisation layer, and standardised evaluation on F1-score for clinical reliability.",
      "Identified and deployed the best-performing architecture, leaving behind a repeatable, scalable model-development lifecycle for the next imaging phase.",
    ],
  },
  {
    id: "road-survey",
    name: "NHAI Road Survey",
    kicker: "Automating Highway Asset Surveys with AI Image Recognition",
    org: "Unthinkable Solutions — Client: NHAI (On-Prem Deployment)",
    categories: ["cv", "civil"],
    tags: ["Object Detection", "On-Prem Deployment", "Multiprocessing"],
    video: "assets/media/roadsurvey.mp4",
    poster: "assets/media/roadsurvey-poster.jpg",
    hook: "An on-prem detection pipeline that reads highway assets straight into NHAI's inventory system.",
    stats: [
      { value: "38", label: "Distinct asset categories" },
      { value: "95%", label: "Less throughput time" },
      { value: "54%", label: "Increase vs. manual" },
    ],
    challenge: [
      "Manually identifying highway assets for NHAI's inventory was labour-intensive, needed detection across many infrastructure categories, and large image volumes slowed processing — with structured reporting still done by hand.",
      "The model had to be deployed on-prem, not in the cloud.",
    ],
    solution: [
      "Built an object detection and classification pipeline trained across 38 asset categories.",
      "Optimised inference with multiprocessing to handle large image volumes.",
      "Automated inventory report generation end to end.",
    ],
  },
  {
    id: "greenspace",
    name: "Urban Green Space",
    kicker: "Geospatial AI — Monitoring Urban Green Space from Space",
    org: "Unthinkable Solutions — Client Engagement",
    categories: ["cv", "geospatial"],
    tags: ["Satellite Imagery", "Model Ensembling", "AWS"],
    video: "assets/media/greenspace.mp4",
    poster: "assets/media/greenspace-poster.jpg",
    hook: "Satellite-scale tree inventory — geo-coordinates, crown area, and health stats for city greenery that often doesn't outlive a mortgage.",
    stats: [
      { value: "90%", label: "Tree-detection accuracy" },
      { value: "30+", label: "Cities mapped" },
      { value: "11+", label: "Models ensembled" },
    ],
    challenge: [
      "Urban trees live roughly 13 years versus 100+ for rural trees, and there was no AI-powered way to detect green areas across varying spatial and spectral resolutions.",
      "The client needed tree inventory delivered as geo-coordinates, crown area, and health statistics — not raw imagery.",
    ],
    solution: [
      "Acquired and chunked satellite provider data, then located each tree precisely and identified its crown area and spread.",
      "Ensembled multiple models to deliver accurate detection across resolutions, and deployed the solution on AWS.",
    ],
  },
  {
    id: "jewelry-bg",
    name: "Jewelry Background Removal",
    kicker: "Automated Image Background Removal for E-commerce Jewelry",
    org: "Unthinkable Solutions — Client Engagement",
    categories: ["cv", "retail"],
    tags: ["Image Segmentation", "Transfer Learning", "Bulk Processing"],
    video: "assets/media/jewelry.mp4",
    poster: "assets/media/jewelry-poster.jpg",
    hook: "Replaced a Photoshop-studio bottleneck with a segmentation model that keeps shine and fine detail intact across rings, necklaces, and earrings.",
    stats: [
      { value: "75%", label: "Less image-editing time" },
      { value: "98%", label: "Increase in op. efficiency" },
      { value: "95%+", label: "Background-removal accuracy" },
    ],
    challenge: [
      "Manual background removal with Photoshop experts was slow and resource-heavy, and preserving jewelry's colour, shine, and fine detail through that process was difficult.",
      "Training data was limited, and lighting/backgrounds varied across rings, necklaces, and earrings alike.",
    ],
    solution: [
      "Built an AI image-segmentation model to separate jewelry from its background automatically.",
      "Used transfer learning to hit high accuracy despite limited training data, with edge-detection and fine-grained masking for detail preservation.",
      "Designed a scalable bulk-processing pipeline that sped up onboarding for new sellers.",
    ],
  },
  {
    id: "property-pipeline",
    name: "Property Data Pipeline",
    kicker: "Cloud-Native ETL for a Property Data Platform",
    org: "Unthinkable Solutions — Client Engagement",
    categories: ["data"],
    tags: ["AWS Glue", "Secrets Manager", "Lambda", "GitHub Actions"],
    hook: "Ingestion-to-transformation ETL on AWS Glue with CI/CD baked in, cutting transformation cost by 80%.",
    stats: [
      { value: "80%", label: "Lower transformation cost" },
    ],
    challenge: [
      "The platform needed secure ingestion from S3, orchestrated ETL, and automated transformation — without runaway compute cost or fragile deploys.",
    ],
    solution: [
      "Spearheaded end-to-end data management: secure S3 ingestion, orchestrated ETL on AWS Glue, and automated transformation, landing an 80% optimisation in transformation cost.",
      "Built CI/CD pipelines with GitHub Actions to streamline ETL script deployment to Glue while keeping data integrity intact.",
      "Used AWS Secrets Manager and Lambda (via Boto3) to harden security, tune ETL performance, and give backend users efficient job management.",
    ],
  },
];

/* Category filter chips shown above the project grid.
   `key` must match an entry in each project's `categories` array. */
const CATEGORIES = [
  { key: "all", label: "All work" },
  { key: "agentic", label: "Agentic AI" },
  { key: "genai", label: "Generative AI" },
  { key: "cv", label: "Computer Vision" },
  { key: "data", label: "Data Engineering" },
  { key: "geospatial", label: "Geospatial" },
  { key: "healthcare", label: "Healthcare" },
  { key: "retail", label: "Retail & E-commerce" },
  { key: "manufacturing", label: "Manufacturing" },
  { key: "civil", label: "Civil Infrastructure" },
];
